// <auto-generated />
using BudgetApp.Data;
using BudgetApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BudgetApp.Migrations
{
    [DbContext(typeof(BudgetAppDbContext))]
    [Migration("20180617153625_Expenses")]
    partial class Expenses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetApp.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("Balance");

                    b.Property<string>("Name");

                    b.Property<string>("Percent");

                    b.Property<int>("Type");

                    b.HasKey("ExpenseID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BudgetApp.Models.Income", b =>
                {
                    b.Property<int>("IncomeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("IncomeID");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("BudgetApp.Models.Saving", b =>
                {
                    b.Property<int>("SavingID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("Goal");

                    b.Property<string>("Name");

                    b.Property<string>("TotalSaved");

                    b.Property<int>("Type");

                    b.HasKey("SavingID");

                    b.ToTable("Savings");
                });

            modelBuilder.Entity("BudgetApp.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LogInName");

                    b.Property<string>("Password1");

                    b.Property<string>("Password2");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
